---
title: "Abstracts Of Opinion Research"
format:
  revealjs:
    logo: https://www.opinion-network.eu/img/opinion_i.gif
    footer: "OPINION | Measuring Opinionated Communication"
---


# get annotated papers

```{r setup}
#| include: false
if (!rlang::is_installed("annotinder")) remotes::install_github("ccs-amsterdam/annotinder-r")
if (!rlang::is_installed("rdrop2")) remotes::install_github("karthik/rdrop2")
library(annotinder)
library(tidyverse); theme_set(hrbrthemes::theme_ipsum_rc())
library(googledrive)
library(glue)
library(rdrop2)
backend_connect(host = "https://cost-tools.up.railway.app",
                username = "johannesb.gruber@gmail.com",
                .password = Sys.getenv("ANNOTINDER_PW"))

coded_abstracts_file <- "../data/abstracts_coded.csv"
if (!file.exists(coded_abstracts_file)) {
  drive_deauth()
  drive_download("https://drive.google.com/file/d/1E9AXyeDoGhLdWSIvnHxAQDi-YqVnzMrT",
                 coded_abstracts_file)
}
data <- read_csv2(coded_abstracts_file) |> 
  mutate(file = gsub("/", "_", paste0(doi, ".pdf"), fixed = TRUE))

# drop_list_shared_links does notwork properly. I redefine it here
drop_list_shared_links2 <- function(path = NULL, verbose = TRUE) {
  dtoken <- rdrop2::drop_auth(rdstoken = "../rdrop-token.rds")
  res <- list(has_more = TRUE)
  links <- list()
  data <- list(path = path)
  
  while (res$has_more) {
    res <- "https://api.dropboxapi.com/2/sharing/list_shared_links" |> 
      httr::POST(httr::config(token = dtoken), encode = "json", body = data) |> 
      httr::stop_for_status() |> 
      httr::content()
    data <- list(cursor = res$cursor)
    links <- c(links, res$links)
  }
  
  purrr::map(links, function(l) {
    tibble(
      id = l$id,
      url = l$url,
      name = l$name,
      path = l$path_lower,
      size = l$size,
      tag = l$.tag,
      link_permissions = list(l$link_permissions)
    )
  }) |> 
    purrr::list_rbind()
  
}
```

# Make sure all PDFs have a share link

```{r}
if (file.exists("../rdrop-token.rds")) {
  pdfs <- drop_dir("opinion_pdfs", dtoken = readRDS("../rdrop-token.rds")) |> 
    filter(.tag == "file") |> 
    select(name, path = path_lower) |> 
    # only take the pdfs of relevant cases
    filter(name %in% data$file)
  shared_df <- drop_list_shared_links2()
  not_shared_df <- shared_df |> 
    filter(str_detect(path, fixed("/opinion_pdfs/"))) |> 
    right_join(pdfs, by = "path") |> 
    filter(is.na(id))
  
  for (i in cli::cli_progress_along(
    not_shared_df$path,
    format = "Sharing pdfs {cli::pb_current}/{cli::pb_total} {cli::pb_eta}"
  )) {
    o <- drop_share(not_shared_df$path[i])
  }
  cli::cli_progress_done()
  shared_df <- drop_list_shared_links2() |> 
    filter(str_detect(path, fixed("/opinion_pdfs/"))) |> 
    select(name, url) |> 
    mutate(url = str_replace(url, "&dl=0", "&dl=1"))
  saveRDS(shared_df, "1._shared_pdfs_df.rds")
} else {
  shared_df <- readRDS("1._shared_pdfs_df.rds")
}
```

# attach existing share links to data

```{r}
data_papers <- data |> 
  filter(!is.na(doi)) |> 
  inner_join(shared_df, by = c("file" = "name"))
```

# codebook

```{r}
welcome <- create_unit(
  "id",
  type = "train",
  set_text("text", "Welcome to AnnoTinder!"),
  set_question(name = "welcome", question = "Who are you", type = "inputs")
)

q10 <- question(
  name = "Q1_0_Tool-Mentioned", 
  question = "Is an Opinion Measurement Tool (OMT) applied or developed in this paper?", 
  codes = list(
    code("No (or unclear)", color = "crimson", makes_irrelevant = "REMAINING"),
    code("Yes", color = "lightgreen")
  )
)
q11 <- question(
  name = "Q1_1_Tool-Name", 
  question = "What is the name of the Opinion Measurement Tool (OMT) applied or developed in this paper?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q12 <- question(
  name = "Q1_2_Tool-Link", 
  question = "What link is reported for the tool?", 
  type = "inputs", 
  instruction = "- if no link is present, separate links for multiple with ;"
)
q13 <- question(
  name = "Q1_3_Tool-Reference", 
  question = "What reference is reported for the tool?", 
  type = "inputs", 
  instruction = "- if no link is present, separate links for multiple with ;"
)

### Question 2
q20 <- question(
  name = "Q2_0_Tool-Mentioned", 
  question = "Are there (additional) tools reviewed (e.g., in the related work section)?", 
  codes = list(
    code("No (or unclear)", color = "crimson", makes_irrelevant = c("Q2_1_Tool-Name",
                                                                    "Q2_2_Tool-Link",
                                                                    "Q2_3_Tool-Reference")),
    code("Yes", color = "lightgreen")
  )
)
q21 <- question(
  name = "Q2_1_Tool-Name", 
  question = "What is the name of the Opinion Measurement Tool (OMT) applied or developed in this paper?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q22 <- question(
  name = "Q2_2_Tool-Link", 
  question = "What link is reported for the tool?", 
  type = "inputs", 
  instruction = "- if no link is present, separate links for multiple with ;"
)
q23 <- question(
  name = "Q2_3_Tool-Reference", 
  question = "What reference is reported for the tool?", 
  type = "inputs", 
  instruction = "- if no link is present, separate links for multiple with ;"
)

### Question 3
q31 <- question(
  name = "Q3_1_Approach", 
  question = "What approach for measuring opinions (or related concepts) is used in the paper? Select all that are applicable?", 
   codes = list(
    code("Dictionaries", makes_irrelevant = "Q3_1_Approach-other"),
    code("Classic Supervised Machine Learning (i.e., usually bag-of-words pre-processing, no deep learning or transformers)", makes_irrelevant = "Q3_1_Approach-other"),
    code("Classic Unsupervised Machine Learning (e.g., topic modeling)", makes_irrelevant = "Q3_1_Approach-other"),
    code("Deep learning/Embeddings, Transformers etc", makes_irrelevant = "Q3_1_Approach-other"),
    code("Proprietary and unclear", makes_irrelevant = "Q3_1_Approach-other"),
    code("Combination of approaches", makes_irrelevant = "Q3_1_Approach-other"),
    code("Unclear", makes_irrelevant = "Q3_1_Approach-other"),
    code("Other or multiple")
  ),
  type = "dropdown"
)
q31_mult <- question(
  name = "Q3_1_Approach-other", 
  question = "Does the measurement approach include a target-specific approach (e.g., measuring sentiment related to a specific keyword, topic, etc.) or not (e.g., using a sentiment dictionary on the whole text indicriminently, etc.)?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q32 <- question(
  name = "Q3_2_Target-specific-Measurement", 
  question = "Does the measurement approach include a target-specific approach (e.g., measuring sentiment related to a specific keyword, topic, etc.) or not (e.g., using a sentiment dictionary on the whole text indicriminently, etc.)?", 
  codes = list(
    code("No (or unclear)", color = "crimson"),
    code("Yes", color = "lightgreen")
  )
)
q33 <- question(
  name = "Q3_3_Validation", 
  question = "Do the authors report validation of their opinion measurement?", 
  codes = list(
    code("No (or unclear)", color = "crimson"),
    code("Yes", color = "lightgreen")
  )
)

### Question 4
q41 <- question(
  name = "Q4_1_Opinion-Evaluation", 
  question = "What subjective evaluation, belief, or feeling is measured?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q42 <- question(
  name = "Q4_2_Opinion-Target", 
  question = "Which particular entity, topic, event, or aspect thereof related to opinion is measured?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)

### Question 5
q50 <- question(
  name = "Q5_0_Data-Mentioned", 
  question = "Does the paper mention or hint which data(set) was analysed?", 
  codes = list(
    code("No (or unclear)", color = "crimson", makes_irrelevant = "REMAINING"),
    code("Yes", color = "lightgreen")
  )
)
q51 <- question(
  name = "Q5_1_Data-Source", 
  question = "Where did the dataset come from?", 
  codes = c(
    "benchmark dataset (e.g., SemEval2013)",
    "Social Media",
    "Media",
    "Governmental texts ",
    "Online Reviews",
    "Personal Communication (e.g., emails, messenger texts)",
    "Other (write in)"
  )
)
q52 <- question(
  name = "Q5_2_Data-Language", 
  question = "Which natural language are the measured opinions expressed in?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q53 <- question(
  name = "Q5_3_Data-Country", 
  question = "Does the dataset cover specific countries?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q54 <- question(
  name = "Q5_4_Dataset-Name", 
  question = "What is/are the name(s) of the data(sets) analysed in this paper?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q55 <- question(
  name = "Q5_5_Other-Dataset-Name", 
  question = "What is/are the name(s) of other data(sets) mentioned in this paper?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q56 <- question(
  name = "Q5_6_Dataset-Link", 
  question = "What link is reported for the dataset (if any)?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)
q57 <- question(
  name = "Q5_7_Dataset-Reference", 
  question = "What reference is reported for the dataset (if any)?", 
  type = "inputs", 
  instruction = "separate multiple tools with ; "
)

# ls(pattern = "q\\d{2}")
codebook <-  create_codebook(q10, q11, q12, q13, q20, q21, q22, q23, 
                             q31, q32, q33,
                             q41, q42,
                             q50, q51, q52, q53, q54, q55, q56, q57)
```

# Units

```{r}
set.seed(1)
units <- data_papers |> 
  sample_n(size = 30L) |> 
  mutate(
    title = glue("**{title}**\n*{author}*"),
    unit = glue("{abstract}\n\n[paper]({url})")
  ) |> 
  create_units(id = "unit_id", 
               set_markdown("headline", title),
               set_markdown("text", unit))
```


# Uplaod

```{r}
backend_connect(host = "https://cost-tools.up.railway.app",
                username = "johannesb.gruber@gmail.com",
                .password = Sys.getenv("ANNOTINDER_PW"))

job_id <- upload_job(
  title = "wg2-paper-annotation",
  units = units,
  debrief = debrief("Thank you for your participation in the coding task! You can add your name to the list of co-authors if you haven't done so yet", 
                    link = "https://docs.google.com/spreadsheets/d/1dk6LlYgliuD0OdF5p7_UAXeVrNDqiFkTtooX-BLh8Xs/edit?usp=sharing",
                    link_text = "Google Sheet of coauthors"),
  # pre = welcome,
  codebook = codebook,
  rules = rules_fixedset()
)
job_id
```

