---
title: ICR OPINION WG2
author: Johannes B. Gruber
date: today
format: html
---

# Introduction

```{r setup}
#| include: false
if (!rlang::is_installed("annotinder")) remotes::install_github("ccs-amsterdam/annotinder-r")
library(annotinder)
library(tidyverse); theme_set(hrbrthemes::theme_ipsum_rc())
library(tidycomm)
library(gt)
library(googledrive)

shared_df <- readRDS("1._shared_pdfs_df.rds")

coded_abstracts_file <- "../data/abstracts_coded.csv"
if (!file.exists(coded_abstracts_file)) {
  drive_deauth()
  drive_download("https://drive.google.com/file/d/1E9AXyeDoGhLdWSIvnHxAQDi-YqVnzMrT",
                 coded_abstracts_file)
}
coded_abstracts_data <- read_csv2(coded_abstracts_file) |> 
  mutate(file = gsub("/", "_", paste0(doi, ".pdf"), fixed = TRUE)) |> 
  left_join(shared_df, by = c(file = "name")) |> 
  select(unit_id, file, url) |> 
  mutate(unit_id = as.character(unit_id))


# if you are me and have the password, load new data, otherwise load it from the repo
if (Sys.getenv("ANNOTINDER_PW") != "") {
  backend_connect(host = "https://cost-tools.up.railway.app",
                  username = "johannesb.gruber@gmail.com",
                  .password = Sys.getenv("ANNOTINDER_PW"))
  data_coded <- download_annotations(57L) |> 
    left_join(coded_abstracts_data, by = "unit_id")
  
  saveRDS(data_coded, "../data/paper-annotation.rds")
} else {
  data_coded <- readRDS("../data/paper-annotation.rds")
}
```

## Export in wide format

```{r}
original_order <- data_coded |> 
  select(unit_id) |> 
  distinct() |> 
  mutate(unit_order = row_number())

data_coded |> 
  select(unit_id, coder, variable, value) |> 
  group_by(unit_id, variable) |> 
  mutate(agreement = length(unique(value)) == 1L) |> 
  pivot_wider(id_cols = c(unit_id, variable, agreement), names_from = coder, values_from = value) |> 
  left_join(original_order, by = "unit_id") |> 
  arrange(unit_order, variable) |> 
  select(-unit_order) |> 
  left_join(coded_abstracts_data, by = "unit_id") |> 
  rio::export("4._annotations.xlsx")
```

